spring.application.name=AuthApp
spring.datasource.url=jdbc:mysql://localhost:3306/gluudb
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.show-aql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.client.registration.gluu.client-id=49966d24-5e9d-4b1b-b888-7dd97c474bd7
spring.security.oauth2.client.registration.gluu.client-secret=4acI3f8uhK0T4vzGhoCuriDf9Rp9yKxmLt29ZFDt
spring.security.oauth2.client.registration.gluu.scope=openid,profile,email,phone
spring.security.oauth2.client.registration.gluu.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gluu.redirect-uri=http://localhost:8080/login/oauth2/code/gluu

spring.security.oauth2.client.provider.gluu.issuer-uri=https://sso.cnxy.in
spring.security.oauth2.client.provider.cnxy.authorization-uri=https://sso.cnxy.in/oxauth/restv1/authorize
spring.security.oauth2.client.provider.cnxy.token-uri=https://sso.cnxy.in/oxauth/restv1/token
spring.security.oauth2.client.provider.cnxy.jwk-set-uri=https://sso.cnxy.in/oxauth/restv1/jwks
spring.security.oauth2.client.provider.cnxy.user-info-uri=https://sso.cnxy.in/oxauth/restv1/userinfo
spring.security.oauth2.client.provider.cnxy.user-name-attribute=sub
