spring.application.name=AuthApp
spring.datasource.url=jdbc:mysql://localhost:3306/database_name
spring.datasource.username=mysql_username
spring.datasource.password=mysql_password
spring.jpa.show-aql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.security.oauth2.client.registration.gluu.client-id=client_id
spring.security.oauth2.client.registration.gluu.client-secret=client_secret
spring.security.oauth2.client.registration.gluu.scope=openid,profile,email,phone
spring.security.oauth2.client.registration.gluu.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.gluu.redirect-uri=http://localhost:8080/login/oauth2/code/gluu

spring.security.oauth2.client.provider.gluu.issuer-uri=your gluu server uri               
spring.security.oauth2.client.provider.gluu.authorization-uri=your gluu server authorize uri
spring.security.oauth2.client.provider.gluu.token-uri=your gluu server token uri
spring.security.oauth2.client.provider.gluu.jwk-set-uri=your gluu server jwks uri
spring.security.oauth2.client.provider.gluu.user-info-uri=your gluu server userinfo uri
spring.security.oauth2.client.provider.gluu.user-name-attribute=sub
